// <auto-generated />
using System;
using LOT5RDB.Data.EquipmentDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LOT5RDB.Data.Migrations.EquipmentDb
{
    [DbContext(typeof(EquipmentDbContext))]
    [Migration("20220520215643_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ItemQualityModelWeaponModel", b =>
                {
                    b.Property<int>("QualitiesId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponsId")
                        .HasColumnType("int");

                    b.HasKey("QualitiesId", "WeaponsId");

                    b.HasIndex("WeaponsId");

                    b.ToTable("WeaponItemQualities", "Equipment");

                    b.HasData(
                        new
                        {
                            QualitiesId = 8,
                            WeaponsId = 1
                        },
                        new
                        {
                            QualitiesId = 1,
                            WeaponsId = 2
                        },
                        new
                        {
                            QualitiesId = 10,
                            WeaponsId = 2
                        },
                        new
                        {
                            QualitiesId = 13,
                            WeaponsId = 4
                        },
                        new
                        {
                            QualitiesId = 1,
                            WeaponsId = 6
                        },
                        new
                        {
                            QualitiesId = 10,
                            WeaponsId = 6
                        },
                        new
                        {
                            QualitiesId = 1,
                            WeaponsId = 7
                        },
                        new
                        {
                            QualitiesId = 10,
                            WeaponsId = 7
                        },
                        new
                        {
                            QualitiesId = 6,
                            WeaponsId = 8
                        },
                        new
                        {
                            QualitiesId = 10,
                            WeaponsId = 8
                        },
                        new
                        {
                            QualitiesId = 1,
                            WeaponsId = 9
                        },
                        new
                        {
                            QualitiesId = 10,
                            WeaponsId = 9
                        },
                        new
                        {
                            QualitiesId = 3,
                            WeaponsId = 10
                        },
                        new
                        {
                            QualitiesId = 16,
                            WeaponsId = 10
                        },
                        new
                        {
                            QualitiesId = 8,
                            WeaponsId = 11
                        },
                        new
                        {
                            QualitiesId = 16,
                            WeaponsId = 12
                        },
                        new
                        {
                            QualitiesId = 8,
                            WeaponsId = 13
                        },
                        new
                        {
                            QualitiesId = 8,
                            WeaponsId = 14
                        },
                        new
                        {
                            QualitiesId = 2,
                            WeaponsId = 15
                        },
                        new
                        {
                            QualitiesId = 8,
                            WeaponsId = 15
                        },
                        new
                        {
                            QualitiesId = 3,
                            WeaponsId = 16
                        },
                        new
                        {
                            QualitiesId = 16,
                            WeaponsId = 16
                        },
                        new
                        {
                            QualitiesId = 3,
                            WeaponsId = 17
                        },
                        new
                        {
                            QualitiesId = 6,
                            WeaponsId = 17
                        },
                        new
                        {
                            QualitiesId = 16,
                            WeaponsId = 17
                        },
                        new
                        {
                            QualitiesId = 2,
                            WeaponsId = 18
                        },
                        new
                        {
                            QualitiesId = 13,
                            WeaponsId = 18
                        },
                        new
                        {
                            QualitiesId = 8,
                            WeaponsId = 19
                        },
                        new
                        {
                            QualitiesId = 2,
                            WeaponsId = 19
                        },
                        new
                        {
                            QualitiesId = 6,
                            WeaponsId = 19
                        },
                        new
                        {
                            QualitiesId = 1,
                            WeaponsId = 21
                        },
                        new
                        {
                            QualitiesId = 2,
                            WeaponsId = 21
                        },
                        new
                        {
                            QualitiesId = 3,
                            WeaponsId = 22
                        },
                        new
                        {
                            QualitiesId = 6,
                            WeaponsId = 22
                        },
                        new
                        {
                            QualitiesId = 16,
                            WeaponsId = 22
                        },
                        new
                        {
                            QualitiesId = 8,
                            WeaponsId = 23
                        },
                        new
                        {
                            QualitiesId = 13,
                            WeaponsId = 24
                        },
                        new
                        {
                            QualitiesId = 16,
                            WeaponsId = 24
                        },
                        new
                        {
                            QualitiesId = 3,
                            WeaponsId = 25
                        },
                        new
                        {
                            QualitiesId = 10,
                            WeaponsId = 25
                        },
                        new
                        {
                            QualitiesId = 16,
                            WeaponsId = 25
                        },
                        new
                        {
                            QualitiesId = 13,
                            WeaponsId = 26
                        },
                        new
                        {
                            QualitiesId = 16,
                            WeaponsId = 26
                        },
                        new
                        {
                            QualitiesId = 16,
                            WeaponsId = 27
                        },
                        new
                        {
                            QualitiesId = 16,
                            WeaponsId = 28
                        },
                        new
                        {
                            QualitiesId = 16,
                            WeaponsId = 29
                        },
                        new
                        {
                            QualitiesId = 9,
                            WeaponsId = 31
                        },
                        new
                        {
                            QualitiesId = 16,
                            WeaponsId = 31
                        },
                        new
                        {
                            QualitiesId = 2,
                            WeaponsId = 32
                        },
                        new
                        {
                            QualitiesId = 2,
                            WeaponsId = 33
                        },
                        new
                        {
                            QualitiesId = 2,
                            WeaponsId = 34
                        },
                        new
                        {
                            QualitiesId = 13,
                            WeaponsId = 34
                        },
                        new
                        {
                            QualitiesId = 16,
                            WeaponsId = 34
                        },
                        new
                        {
                            QualitiesId = 2,
                            WeaponsId = 35
                        });
                });

            modelBuilder.Entity("LOT5RDB.Equipment.Shared.ItemQualities.Models.ItemQualityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("DescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemQualities", "Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionId = new Guid("fc81b4aa-eb77-48d1-aa72-e6664b30a5bc"),
                            IsActive = true,
                            Name = "Ceremonial"
                        },
                        new
                        {
                            Id = 2,
                            DescriptionId = new Guid("dfd36c34-9c81-4e52-b0cf-354bb949cbc2"),
                            IsActive = true,
                            Name = "Concealable"
                        },
                        new
                        {
                            Id = 3,
                            DescriptionId = new Guid("89d3bcfd-2c6b-4477-9494-325e62b84575"),
                            IsActive = true,
                            Name = "Cumbersome"
                        },
                        new
                        {
                            Id = 4,
                            DescriptionId = new Guid("93ddcfac-65eb-4597-a7f0-21597d483715"),
                            IsActive = true,
                            Name = "Damaged"
                        },
                        new
                        {
                            Id = 5,
                            DescriptionId = new Guid("6b101e42-cdaa-4f31-8bfd-25bd104c7d30"),
                            IsActive = true,
                            Name = "Destroyed"
                        },
                        new
                        {
                            Id = 6,
                            DescriptionId = new Guid("f677c10e-4f44-489d-93ff-32338d326b4f"),
                            IsActive = true,
                            Name = "Durable"
                        },
                        new
                        {
                            Id = 7,
                            DescriptionId = new Guid("b29bc7f7-1ed8-42b1-99e9-37e0c2cefda7"),
                            IsActive = true,
                            Name = "Forbidden"
                        },
                        new
                        {
                            Id = 8,
                            DescriptionId = new Guid("a6aa065e-374f-41e3-a86a-004b18093c4e"),
                            IsActive = true,
                            Name = "Mundane"
                        },
                        new
                        {
                            Id = 9,
                            DescriptionId = new Guid("7c6be140-ec3a-4e92-9f72-95976aae917f"),
                            IsActive = true,
                            Name = "Prepare"
                        },
                        new
                        {
                            Id = 10,
                            DescriptionId = new Guid("16bd58e5-32d8-4e38-a864-accb556e923d"),
                            IsActive = true,
                            Name = "Razor-Edged"
                        },
                        new
                        {
                            Id = 11,
                            DescriptionId = new Guid("28dd5718-b1cd-4217-9d1e-51a560bdb812"),
                            IsActive = true,
                            Name = "Resplendent"
                        },
                        new
                        {
                            Id = 12,
                            DescriptionId = new Guid("6580f21f-4f76-4987-b1db-8482c17c4ce2"),
                            IsActive = true,
                            Name = "Sacred"
                        },
                        new
                        {
                            Id = 13,
                            DescriptionId = new Guid("2b44d64a-b5ef-4725-aceb-98b8f3584fdd"),
                            IsActive = true,
                            Name = "Snaring"
                        },
                        new
                        {
                            Id = 14,
                            DescriptionId = new Guid("c569f579-5097-49ad-8411-58692e36c642"),
                            IsActive = true,
                            Name = "Subtle"
                        },
                        new
                        {
                            Id = 15,
                            DescriptionId = new Guid("03861fad-00e7-4979-8f0f-b1c4e0559b93"),
                            IsActive = true,
                            Name = "Unholy"
                        },
                        new
                        {
                            Id = 16,
                            DescriptionId = new Guid("03861fad-00e7-4979-8f0f-b1c4e0559b93"),
                            IsActive = true,
                            Name = "Wargear"
                        });
                });

            modelBuilder.Entity("LOT5RDB.Equipment.Shared.Weapons.Models.WeaponModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BaseDamage")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Deadliness")
                        .HasColumnType("int");

                    b.Property<Guid>("DescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Grips")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("Weapons", "Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseDamage = 3,
                            Category = 1,
                            Deadliness = 3,
                            DescriptionId = new Guid("9d785089-f4a0-447a-86ae-0846dcfdd7af"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]},{\"GripType\":2,\"Bonus\":\"Damage +2\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Bokken",
                            Price = 10,
                            Range = "1-1",
                            Rarity = 3,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 2,
                            BaseDamage = 4,
                            Category = 1,
                            Deadliness = 5,
                            DescriptionId = new Guid("7bd3e03d-b9fc-4ef4-b9bc-a582434a14db"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Chokutō",
                            Price = 2000,
                            Range = "0-1",
                            Rarity = 7,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 3,
                            BaseDamage = 4,
                            Category = 1,
                            Deadliness = 5,
                            DescriptionId = new Guid("3be3c2ec-ffe7-4304-a7d1-c1f3a3afcee0"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Dao",
                            Price = 1500,
                            Range = "1-1",
                            Rarity = 6,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 4,
                            BaseDamage = 4,
                            Category = 1,
                            Deadliness = 3,
                            DescriptionId = new Guid("fdc8a246-abc4-4e1d-af89-2822acf8f03d"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Gao",
                            Price = 1500,
                            Range = "1-1",
                            Rarity = 7,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 5,
                            BaseDamage = 4,
                            Category = 1,
                            Deadliness = 4,
                            DescriptionId = new Guid("4d19ac97-1238-47af-ab8a-2eaae450816e"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]},{\"GripType\":2,\"Bonus\":\"Deadliness +1\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Jian",
                            Price = 1500,
                            Range = "0-1",
                            Rarity = 7,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 6,
                            BaseDamage = 4,
                            Category = 1,
                            Deadliness = 5,
                            DescriptionId = new Guid("8761953c-0d1f-4edc-8860-aa949c22c39c"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]},{\"GripType\":2,\"Bonus\":\"Deadliness +2\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Katana",
                            Price = 2000,
                            Range = "1-1",
                            Rarity = 7,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 7,
                            BaseDamage = 5,
                            Category = 1,
                            Deadliness = 6,
                            DescriptionId = new Guid("64dc8d84-22d1-4aeb-bdce-3efcd4fd839a"),
                            Grips = "[{\"GripType\":2,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Nodachi",
                            Price = 2000,
                            Range = "1-2",
                            Rarity = 8,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 8,
                            BaseDamage = 4,
                            Category = 1,
                            Deadliness = 5,
                            DescriptionId = new Guid("7bf856dd-db5f-42fa-89cf-9c84dac758d4"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Scimitar",
                            Price = 2000,
                            Range = "1-1",
                            Rarity = 8,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 9,
                            BaseDamage = 3,
                            Category = 1,
                            Deadliness = 5,
                            DescriptionId = new Guid("272aaed4-e935-449b-bec0-a1f307d0dbfd"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]},{\"GripType\":2,\"Bonus\":\"Deadliness +2\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Wakizashi",
                            Price = 1500,
                            Range = "0-1",
                            Rarity = 7,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 10,
                            BaseDamage = 6,
                            Category = 1,
                            Deadliness = 7,
                            DescriptionId = new Guid("725d0771-5ef1-4e96-8f4d-65630ee5094e"),
                            Grips = "[{\"GripType\":2,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Zanbatō",
                            Price = 4000,
                            Range = "1-2",
                            Rarity = 8,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 11,
                            BaseDamage = 3,
                            Category = 2,
                            Deadliness = 4,
                            DescriptionId = new Guid("ca8cd8c7-de5a-4f41-9a91-5c2c9c75119a"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]},{\"GripType\":2,\"Bonus\":\"Deadliness +2\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Masakari",
                            Price = 30,
                            Range = "0-1",
                            Rarity = 5,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 12,
                            BaseDamage = 5,
                            Category = 2,
                            Deadliness = 6,
                            DescriptionId = new Guid("ef557f8f-149d-4f10-8759-a1d6b7e6968b"),
                            Grips = "[{\"GripType\":2,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Ono",
                            Price = 500,
                            Range = "1-2",
                            Rarity = 7,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 13,
                            BaseDamage = 5,
                            Category = 3,
                            Deadliness = 2,
                            DescriptionId = new Guid("39aab287-beaf-40e4-a145-64b262a85888"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]},{\"GripType\":2,\"Bonus\":\"Damage +1\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Club",
                            Price = 10,
                            Range = "0-1",
                            Rarity = 1,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 14,
                            BaseDamage = 5,
                            Category = 3,
                            Deadliness = 2,
                            DescriptionId = new Guid("c6fbcb03-9201-4aa0-b63a-640c727950f6"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]},{\"GripType\":2,\"Bonus\":\"Damage +2\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Hammer",
                            Price = 20,
                            Range = "0-1",
                            Rarity = 4,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 15,
                            BaseDamage = 2,
                            Category = 3,
                            Deadliness = 2,
                            DescriptionId = new Guid("445ed817-f218-43cc-8160-24cfc7334e55"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Kiseru",
                            Price = 100,
                            Range = "0-0",
                            Rarity = 5,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 16,
                            BaseDamage = 8,
                            Category = 3,
                            Deadliness = 3,
                            DescriptionId = new Guid("309b89e0-272b-429a-ab76-cb976b3b3f88"),
                            Grips = "[{\"GripType\":2,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Ōtsuchi",
                            Price = 3000,
                            Range = "1-1",
                            Rarity = 8,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 17,
                            BaseDamage = 7,
                            Category = 3,
                            Deadliness = 3,
                            DescriptionId = new Guid("b62e8802-baed-4b24-86d4-f95dfdd86c82"),
                            Grips = "[{\"GripType\":2,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Tetsubō",
                            Price = 2000,
                            Range = "1-2",
                            Rarity = 5,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 18,
                            BaseDamage = 3,
                            Category = 4,
                            Deadliness = 2,
                            DescriptionId = new Guid("0403c313-c888-4165-ba3e-ea862f7a02e3"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Jitte",
                            Price = 10,
                            Range = "0-0",
                            Rarity = 5,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 19,
                            BaseDamage = 2,
                            Category = 4,
                            Deadliness = 4,
                            DescriptionId = new Guid("1867197e-7356-4cae-bca8-3c4ff7364100"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]},{\"GripType\":2,\"Bonus\":\"Deadliness +2\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Knife",
                            Price = 100,
                            Range = "0-0",
                            Rarity = 5,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 20,
                            BaseDamage = 4,
                            Category = 4,
                            Deadliness = 3,
                            DescriptionId = new Guid("dc6f6362-ffb4-4875-8014-c2e83dc4ba64"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]},{\"GripType\":2,\"Bonus\":\"Snaring\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Nunchaku",
                            Price = 100,
                            Range = "0-1",
                            Rarity = 6,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 21,
                            BaseDamage = 4,
                            Category = 4,
                            Deadliness = 3,
                            DescriptionId = new Guid("4ef6e7b7-1045-4d4b-afd0-0c394fcabf43"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Tessen",
                            Price = 1500,
                            Range = "0-1",
                            Rarity = 7,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 22,
                            BaseDamage = 5,
                            Category = 5,
                            Deadliness = 2,
                            DescriptionId = new Guid("728a3ba3-343c-47cc-932f-5720aeed4831"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"Range 1\",\"ExtraDescription\":\"\",\"Weapons\":[]},{\"GripType\":2,\"Bonus\":\"Damage +2\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Bisentō",
                            Price = 1500,
                            Range = "2-2",
                            Rarity = 8,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 23,
                            BaseDamage = 6,
                            Category = 5,
                            Deadliness = 2,
                            DescriptionId = new Guid("6061e354-7151-4ad8-b8bc-c2fea19f1cfd"),
                            Grips = "[{\"GripType\":2,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Bō",
                            Price = 20,
                            Range = "1-2",
                            Rarity = 2,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 24,
                            BaseDamage = 5,
                            Category = 5,
                            Deadliness = 2,
                            DescriptionId = new Guid("ca51e607-66be-431c-851c-715dc1622262"),
                            Grips = "[{\"GripType\":2,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Ji",
                            Price = 700,
                            Range = "2-2",
                            Rarity = 6,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 25,
                            BaseDamage = 6,
                            Category = 5,
                            Deadliness = 6,
                            DescriptionId = new Guid("1fc3321f-45d2-4e8d-99c9-abef09c6f3d8"),
                            Grips = "[{\"GripType\":2,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Naginata",
                            Price = 1000,
                            Range = "2-2",
                            Rarity = 8,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 26,
                            BaseDamage = 4,
                            Category = 5,
                            Deadliness = 4,
                            DescriptionId = new Guid("5b09b7f0-fac3-4634-9480-93a8c3c65229"),
                            Grips = "[{\"GripType\":2,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Trident",
                            Price = 1000,
                            Range = "2-2",
                            Rarity = 7,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 27,
                            BaseDamage = 5,
                            Category = 5,
                            Deadliness = 3,
                            DescriptionId = new Guid("63c1b2b5-9a91-402c-8598-135fe17eff75"),
                            Grips = "[{\"GripType\":2,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Yari",
                            Price = 500,
                            Range = "2-2",
                            Rarity = 3,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 28,
                            BaseDamage = 6,
                            Category = 6,
                            Deadliness = 4,
                            DescriptionId = new Guid("ec0d878d-62de-4138-9468-277d0aa95464"),
                            Grips = "[{\"GripType\":2,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Daikyū",
                            Price = 600,
                            Range = "3-5",
                            Rarity = 6,
                            SkillId = 16
                        },
                        new
                        {
                            Id = 29,
                            BaseDamage = 4,
                            Category = 6,
                            Deadliness = 5,
                            DescriptionId = new Guid("d60bdbbe-4b54-40d1-9288-5939090c042d"),
                            Grips = "[{\"GripType\":2,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Shinjo Horsebow",
                            Price = 600,
                            Range = "2-4",
                            Rarity = 4,
                            SkillId = 16
                        },
                        new
                        {
                            Id = 30,
                            BaseDamage = 5,
                            Category = 6,
                            Deadliness = 3,
                            DescriptionId = new Guid("7a8fcfe8-6f94-4098-ba3b-b48b1fd9967d"),
                            Grips = "[{\"GripType\":2,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Yumi",
                            Price = 300,
                            Range = "2-5",
                            Rarity = 3,
                            SkillId = 16
                        },
                        new
                        {
                            Id = 31,
                            BaseDamage = 7,
                            Category = 7,
                            Deadliness = 3,
                            DescriptionId = new Guid("f283fa16-6b2a-4de7-8f6d-91f8cdabd0bd"),
                            Grips = "[{\"GripType\":2,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Oyumi",
                            Price = 400,
                            Range = "2-5",
                            Rarity = 8,
                            SkillId = 16
                        },
                        new
                        {
                            Id = 32,
                            BaseDamage = 1,
                            Category = 8,
                            Deadliness = 2,
                            DescriptionId = new Guid("1d68e56a-6542-4cff-afc7-6807c319a126"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Blowgun",
                            Price = 50,
                            Range = "2-3",
                            Rarity = 7,
                            SkillId = 16
                        },
                        new
                        {
                            Id = 33,
                            BaseDamage = 3,
                            Category = 8,
                            Deadliness = 3,
                            DescriptionId = new Guid("ba0b15cf-5f31-4ea9-9ddf-5af0963a62a9"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Kama",
                            Price = 100,
                            Range = "0-1",
                            Rarity = 4,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 34,
                            BaseDamage = 3,
                            Category = 8,
                            Deadliness = 3,
                            DescriptionId = new Guid("9b5ae25b-49e3-4f8b-bc67-9645b835aca7"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"\",\"Weapons\":[]},{\"GripType\":2,\"Bonus\":\"Range 2-3\",\"ExtraDescription\":\"\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Kusari-Gama",
                            Price = 500,
                            Range = "0-0",
                            Rarity = 6,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 35,
                            BaseDamage = 2,
                            Category = 8,
                            Deadliness = 4,
                            DescriptionId = new Guid("662ac896-8686-4cc1-93f2-ea44e2416b40"),
                            Grips = "[{\"GripType\":1,\"Bonus\":\"-\",\"ExtraDescription\":\"(stab or slash)\",\"Weapons\":[]},{\"GripType\":1,\"Bonus\":\"Martial Arts [Ranged], Range 1-3\",\"ExtraDescription\":\"(thrown)\",\"Weapons\":[]}]",
                            IsActive = true,
                            Name = "Shuriken",
                            Price = 100,
                            Range = "0-0",
                            Rarity = 6,
                            SkillId = 15
                        });
                });

            modelBuilder.Entity("LOT5RDB.Skills.Shared.Models.SkillGroupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("DescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkillGroups", "Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionId = new Guid("03b6062e-7c0e-4ba0-93ab-f3b41c13261b"),
                            IsActive = true,
                            Name = "Artisan"
                        },
                        new
                        {
                            Id = 2,
                            DescriptionId = new Guid("1f28aca2-2231-47cd-b8a9-fa487c3c2c4a"),
                            IsActive = true,
                            Name = "Martial"
                        },
                        new
                        {
                            Id = 3,
                            DescriptionId = new Guid("574fea87-6fc0-488f-b452-22d4cbaf7784"),
                            IsActive = true,
                            Name = "Scholar"
                        },
                        new
                        {
                            Id = 4,
                            DescriptionId = new Guid("758a9a52-f869-49f7-87bd-4234e1018a27"),
                            IsActive = true,
                            Name = "Social"
                        },
                        new
                        {
                            Id = 5,
                            DescriptionId = new Guid("148939ba-86eb-4c5b-8df0-c230f8257589"),
                            IsActive = true,
                            Name = "Trade"
                        });
                });

            modelBuilder.Entity("LOT5RDB.Skills.Shared.Models.SkillModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("DescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillGroupId");

                    b.ToTable("Skills", "Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionId = new Guid("1879583a-b7bb-455d-93d6-b4fbee6078a2"),
                            IsActive = true,
                            Name = "Aesthetics",
                            SkillGroupId = 1
                        },
                        new
                        {
                            Id = 2,
                            DescriptionId = new Guid("d80bc5bf-4931-4fd1-857e-497eccdbf342"),
                            IsActive = true,
                            Name = "Composition",
                            SkillGroupId = 1
                        },
                        new
                        {
                            Id = 3,
                            DescriptionId = new Guid("17a19c61-26cb-433e-aa2e-64a366d31239"),
                            IsActive = true,
                            Name = "Design",
                            SkillGroupId = 1
                        },
                        new
                        {
                            Id = 4,
                            DescriptionId = new Guid("923f8290-f0f3-4e6d-a2de-db55c18540d4"),
                            IsActive = true,
                            Name = "Smithing",
                            SkillGroupId = 1
                        },
                        new
                        {
                            Id = 5,
                            DescriptionId = new Guid("7aa51fd4-3e68-452c-9d74-c2c451d9b1df"),
                            IsActive = true,
                            Name = "Command",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 6,
                            DescriptionId = new Guid("7b29a2b0-36ea-44be-961f-d77bac1418c1"),
                            IsActive = true,
                            Name = "Courtesy",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 7,
                            DescriptionId = new Guid("ea6a04a7-9e1c-4541-b220-5fd28475646f"),
                            IsActive = true,
                            Name = "Games",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 8,
                            DescriptionId = new Guid("aebc434f-6060-47ff-aae8-2455ad957fa0"),
                            IsActive = true,
                            Name = "Performance",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 9,
                            DescriptionId = new Guid("b8e30628-b535-4c91-b168-ccccf49cee88"),
                            IsActive = true,
                            Name = "Culture",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 10,
                            DescriptionId = new Guid("62489655-9d8e-4f19-95ff-53abcdf51a56"),
                            IsActive = true,
                            Name = "Government",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 11,
                            DescriptionId = new Guid("4a494aae-1dc9-49b9-9c88-2aeeed24584e"),
                            IsActive = true,
                            Name = "Medicine",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 12,
                            DescriptionId = new Guid("0882d9c1-323a-42b4-9225-9261b99658db"),
                            IsActive = true,
                            Name = "Sentiment",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 13,
                            DescriptionId = new Guid("6d59586f-7b4e-497f-9db1-b2a403c021ce"),
                            IsActive = true,
                            Name = "Theology",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 14,
                            DescriptionId = new Guid("06ddcb2c-c011-4b2b-bed7-336258a71b26"),
                            IsActive = true,
                            Name = "Fitness",
                            SkillGroupId = 2
                        },
                        new
                        {
                            Id = 15,
                            DescriptionId = new Guid("9bf05308-4c5d-498c-9b83-441934b9879d"),
                            IsActive = true,
                            Name = "Martial Arts [Melee]",
                            SkillGroupId = 2
                        },
                        new
                        {
                            Id = 16,
                            DescriptionId = new Guid("bba94dda-3c39-48f0-b53d-9ba014a0e369"),
                            IsActive = true,
                            Name = "Martial Arts [Ranged]",
                            SkillGroupId = 2
                        },
                        new
                        {
                            Id = 17,
                            DescriptionId = new Guid("c7949ac1-bbc9-4108-8a10-9d10c046e441"),
                            IsActive = true,
                            Name = "Martial Arts [Unarmed]",
                            SkillGroupId = 2
                        },
                        new
                        {
                            Id = 18,
                            DescriptionId = new Guid("f03aa519-4193-4ee1-bd7d-63b469f7bcda"),
                            IsActive = true,
                            Name = "Meditation",
                            SkillGroupId = 2
                        },
                        new
                        {
                            Id = 19,
                            DescriptionId = new Guid("481e4264-f1e6-4112-9e88-bb669fc4fa3c"),
                            IsActive = true,
                            Name = "Tactics",
                            SkillGroupId = 2
                        },
                        new
                        {
                            Id = 20,
                            DescriptionId = new Guid("d457ba6d-8f6c-4a4a-a0dd-f7d229ea7a00"),
                            IsActive = true,
                            Name = "Commerce",
                            SkillGroupId = 5
                        },
                        new
                        {
                            Id = 21,
                            DescriptionId = new Guid("e610bc1e-f62e-4238-90b3-af3e86a14f2f"),
                            IsActive = true,
                            Name = "Labor",
                            SkillGroupId = 5
                        },
                        new
                        {
                            Id = 22,
                            DescriptionId = new Guid("3c7caaa2-7d10-4f98-ab23-051d677d58c1"),
                            IsActive = true,
                            Name = "Seafaring",
                            SkillGroupId = 5
                        },
                        new
                        {
                            Id = 23,
                            DescriptionId = new Guid("faccaf45-a3cd-4c96-ae3e-9bb07a9c9c2d"),
                            IsActive = true,
                            Name = "Skulduggery",
                            SkillGroupId = 5
                        },
                        new
                        {
                            Id = 24,
                            DescriptionId = new Guid("1804a803-48a9-4f32-884f-e9e7787d75dd"),
                            IsActive = true,
                            Name = "Survival",
                            SkillGroupId = 5
                        });
                });

            modelBuilder.Entity("ItemQualityModelWeaponModel", b =>
                {
                    b.HasOne("LOT5RDB.Equipment.Shared.ItemQualities.Models.ItemQualityModel", null)
                        .WithMany()
                        .HasForeignKey("QualitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LOT5RDB.Equipment.Shared.Weapons.Models.WeaponModel", null)
                        .WithMany()
                        .HasForeignKey("WeaponsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LOT5RDB.Equipment.Shared.Weapons.Models.WeaponModel", b =>
                {
                    b.HasOne("LOT5RDB.Skills.Shared.Models.SkillModel", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("LOT5RDB.Skills.Shared.Models.SkillModel", b =>
                {
                    b.HasOne("LOT5RDB.Skills.Shared.Models.SkillGroupModel", "SkillGroup")
                        .WithMany("Skills")
                        .HasForeignKey("SkillGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillGroup");
                });

            modelBuilder.Entity("LOT5RDB.Skills.Shared.Models.SkillGroupModel", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
